spring:
  datasource:
    url: jdbc:postgresql://dpg-d0no6uk9c44c738hts9g-a:5432/mapgenda_db
    username: fernando
    password: Q3RyQIfZgze4IG4FkGQ0o2qO5MTJUBvo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: ${PORT:10000}
