spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mapgenda_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /aventura
