spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aventura_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /aventura

